### PR TITLE
qrexample

### PR DESCRIPTION
**Pull request by jarrodcolburn**
Porting over Flutter Web Chrome Extension [example](https://github.com/jarrodcolburn/chromeapi/tree/main/example) from discontinued [`chromeapi` package](https://pub.dev/packages/chromeapi/example).

### CODE REVIEW

**Comment by jarrodcolburn** [comment]
The options page is just the words Options on a red background. 
image

**Comment by jarrodcolburn** [comment]
Feel free to use as much or as little as you want. One option I was considering was allowing the user to select QR code generator defaults (like color) in the options page that would be saved using the Chrome storage API.

**Comment by jarrodcolburn** [comment]
This example, in addition to using the # tags for options page. Also implements the sizing of pop-up in Dart, rather than hardcoding in `index.html` as described in https://github.com/xvrh/chrome_extension.dart/issues/21#issuecomment-2008155223

**Comment by xvrh** [comment]
Thanks for the contribution! I'll merge it directly.

**Pull request merged**
